### ISSUE TITLE
[Bug]: BackgroundTask running might cause terminate the app

### ISSUE THREAD

**Issue by LucioPham** [braze-inc/braze-swift-sdk#42] opened 2023-02-16 09:11 UTC
### Platform

iOS

### Platform Version

iOS 16.1.1

### Braze SDK Version

5.9.1, 5.10.0

### Xcode Version

Xcode 14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

I upgraded to the latest version with the issue reported here https://github.com/braze-inc/braze-swift-sdk/issues/36 but even with the new version the issue still happens again.

When running the app then put it into the background and then back again to the foreground (sometimes don't need to back to the foreground ) then I got the log from the Xcode console as below.

[BackgroundTask] Background Task 15021 ("http.client: POST /data"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

This issue might cause my app getting to terminate by iOS System.

I'm trying to disable BrazeSDK and never got the log again and my app never gets terminated by iOS System when it is in the background.

I suppose this background task has come from BrazeSDK. Please help me to check on this. Thanks

### Expected Behavior

Not receiving the warning log as below from the console when using BrazeSDK

[BackgroundTask] Background Task 15021 ("http.client: POST /data"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

### Actual Incorrect Behavior

Keep receiving the warning log from the console when using BrazeSDK.

[BackgroundTask] Background Task 15021 ("http.client: POST /data"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

### Verbose Logs

```shell
[BackgroundTask] Background Task 954 ("http.client: POST /data"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

[BackgroundTask] Background Task 684 ("persistence: users/user_id/news-feed"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

[33307:11893997] [BackgroundTask] Background Task 1089 ("http.client: POST /content_cards/sync"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```

**Comment by hokstuff** [comment] 2023-02-16 19:12
Hi @LucioPham,

Thanks for attaching information around this issue. We are tracking it internally and will investigate to find the root cause.

**Comment by hokstuff** [comment] 2023-02-17 22:09
@LucioPham - After some discussion, we would like more information around the issue you are facing to help with the investigation. Can you contact support@braze.com and attach context around:
1. Your integration code with Braze
    - Specifically, we would like to see if you interface with the Braze APIs with any custom code at all that might be affecting performance or causing these tasks to persist
2. Information around your testing environment
    - Are you testing with an older device / simulator, and are you experiencing slow network connection when you see these logs?
3. Are you seeing this error with any other dependencies or running processes?

We can then converse via our Support channel so it is easier and quicker for back-and-forth.

**Comment by hokstuff** [comment] 2023-03-08 16:50
I'm closing out this issue since we are conversing on our Support channel and since this issue pertains to the client's specific custom integration with our SDK.

**Closed by hokstuff** 2023-03-08 16:50 UTC
Labels: bug
